Add substring search
TechOUs/Data-Structures pull request #69
Opened 2020-10-04 20:55 UTC by fazd

I Add the program substring search resolving issue #68

2020-10-05 18:13 UTC, GauravWalia19 requested changes

2020-10-05 18:13 UTC, GauravWalia19 commented on STRING/C++/StringSearch.cpp
> +    /*for(int i = 0; i < n; i++){
Remove this commented code.

2020-10-05 18:13 UTC, GauravWalia19 commented on STRING/C++/StringSearch.cpp
> +    //cout<<"start: "<<start<<" end: "<<end<<" mid: "<<mid<<"\n";
Remove this one also

2020-10-05 18:50 UTC, fazd commented
Checked, I remove both comments

2020-10-05 18:50 UTC, fazd commented on STRING/C++/StringSearch.cpp
> +    //cout<<"start: "<<start<<" end: "<<end<<" mid: "<<mid<<"\n";
Done

2020-10-05 18:50 UTC, fazd commented on STRING/C++/StringSearch.cpp
> +    /*for(int i = 0; i < n; i++){
Done

2020-10-10 04:03 UTC, GauravWalia19 approved these changes

2020-10-10 04:04 UTC, merged